force-app/main/default/objects/Account/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <description>The unique identifier for the author as represented in the marketplace.</description>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>60</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SystemSettings__c/SystemSettings__c.object-meta.xml
<CustomObject>
    <label>System Settings</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>System Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SystemSettings__c/fields/KeyId__c.field-meta.xml
<CustomField>
    <fullName>KeyId__c</fullName>
    <label>Key ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SystemSettings__c/fields/PrivateKey__c.field-meta.xml
<CustomField>
    <fullName>PrivateKey__c</fullName>
    <label>Private Key</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/AuthorReviewsUpdateSchedulerTest.cls
@isTest
public class AuthorReviewsUpdateSchedulerTest {
    @isTest
    public static void account_item_counts_update_successfully() {
        Test.setMock(HttpCalloutMock.class, new PhotoQCClientTest.AuthorDataResponder());
        
        String schedule = '00 00 12 * * ?';
        
        List<Account> testAccounts = new List<Account>{
            new Account(
                Name = 'Test Account',
                UUID__c = '00000000-7357-7357-7357-000000000000'
            )
        };
        
        insert testAccounts;
        
        SystemSettings__c conn = new SystemSettings__c(
            Name = 'PhotoQC',
            Host__c = TestUtil.TEST_HOST,
            KeyId__c = TestUtil.TEST_KEY_ID,
            PrivateKey__c = TestUtil.TEST_PRIVATE_KEY
        );
        
        insert conn;
        
        Test.startTest();
        
        AuthorReviewsUpdateScheduler job = new AuthorReviewsUpdateScheduler();
        ID jobId = System.schedule('Test Author Reviews Update Batch Job', schedule, job);
        
        Test.stopTest();
        
        System.assertNotEquals(null, jobId);
    }
}